name: Build and deploy Node.js app to Azure Web App - GC-Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      # Setup Node 22
      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      # Install dependencies inside backend
      - name: Install dependencies
        run: |
          cd backend
          npm install

      # Build step (optional)
      - name: Build (if present)
        run: |
          cd backend
          npm run build --if-present

      # Upload backend folder as artifact
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: backend

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'GC-Test'
          slot-name: 'Production'
          package: backend
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE }}
