name: Build and deploy Node.js app to Azure Web App - GC-Test

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js 22
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      # 👇 Run npm inside backend folder
      - name: Install dependencies
        run: |
          cd backend
          npm install

      - name: Build (if present)
        run: |
          cd backend
          npm run build --if-present

      - name: Upload backend as artifact
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: backend

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: node-app
      
      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'GC-Test'
          slot-name: 'Production'
          package: backend   # 👈 deploy backend folder
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_938BE7D967A24C5BABF12B2958E2E713 }}
